server.port=8081

debug=true
logging.level.org.springframework.boot.context.config=DEBUG
logging.level.org.springframework.ws.server.endpoint.mapping=DEBUG
logging.level.org.springframework.ws.server.endpoint.adapter=DEBUG

spring.application.name=iis_backend
spring.datasource.url=jdbc:h2:file:./data/testdb;MODE=PostgreSQL;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console