############################################
# Server (REST)
############################################
server.port=8081

############################################
# gRPC server (net.devh grpc-spring-boot-starter)
############################################
grpc.server.port=9090

############################################
# API switch: koristi Okta (public) ili vlastiti DB (custom)
############################################
# okta.api.mode=public
okta.api.mode=custom

############################################
# Okta (PUBLIC mode) - domena i SSWS token
############################################
okta.domain=https://integrator-2485227.okta.com
okta.token=00y6ndfsCUPRNOdbKUhYksE8uYoOUJGIv6JTozp5Cc

############################################
# Database (CUSTOM mode) - primjer s H2
# (Ako koristi? Postgres/MySQL, reci pa prilagodim)
############################################
# PERSISTENT H2 (na disku)
spring.datasource.url=jdbc:h2:file:./data/iis;MODE=PostgreSQL;AUTO_SERVER=TRUE
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# nemoj create-drop jer bri?e sve
spring.jpa.hibernate.ddl-auto=update

# H2 console (optional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

############################################
# JWT (CUSTOM mode): access + refresh
############################################
jwt.secret=fodffdjio3943008w43njjfkfkdjnnfdnjkkjd
jwt.access.ttlSeconds=900
jwt.refresh.ttlSeconds=1209600

############################################
# GraphQL (ako koristi? spring-boot-starter-graphql)
############################################
spring.graphql.path=/graphql
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql