############################################
# tajne
############################################
spring.config.import=optional:file:../config/secrets.properties

############################################
# Server (REST)
############################################
server.port=8081

############################################
# gRPC server (net.devh grpc-spring-boot-starter)
############################################
grpc.server.port=9090
grpc.client.weather.address=static://127.0.0.1:${grpc.server.port}
grpc.client.weather.negotiationType=PLAINTEXT

############################################
# API switch:
############################################
# okta.api.mode=public
okta.api.mode=custom


############################################
# Database - H2 - disk config
############################################
spring.datasource.url=jdbc:h2:file:./data/iis;MODE=PostgreSQL;AUTO_SERVER=TRUE
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

############################################
# JWT: access + refresh
############################################
jwt.access.ttlSeconds=900
jwt.refresh.ttlSeconds=1209600

############################################
# GraphQL
############################################
spring.graphql.path=/graphql
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

